package jcommandgen.api;

public enum ReturnCode {

    OK,
    INCORRECT_INPUT_NUMBER,
    ENGINE_FILE_NOT_SELECTED,
    MIN_LESS_THAN_DEFAULT_MIN, MIN_MORE_THAN_DEFAULT_MAX,
    MAX_MORE_THAN_DEFAULT_MAX, MAX_LESS_THAN_DEFAULT_MIN,
    ENTERED_MIN_LESS_THAN_DEFAULT_MIN, ENTERED_MIN_MORE_THAN_DEFAULT_MAX,
    ENTERED_MAX_LESS_THAN_DEFAULT_MIN, ENTERED_MAX_MORE_THAN_DEFAULT_MAX,
    CMD_FILE_GENERATED, CMD_FILE_NOT_GENERATED,
    CMD_FILE_MODIFIED, CMD_FILE_NOT_MODIFIED,
    EULA_FILE_CREATED, EULA_FILE_NOT_CREATED,
    EULA_FILE_MODIFIED, EULA_FILE_NOT_MODIFIED,
    ACCEPTED, NOT_ACCEPTED

}
